# https://github.com/amannn/action-semantic-pull-request
# Ensures that pull requests have a title that follows the Conventional Commits specification.
name: Lint Pull Request Title
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  lint-pull-request-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
